---
resources:
- name: ExpenseTracker
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}

- name: deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: production

jobs:
- name: build
  plan:
  - get: ExpenseTracker
    trigger: true
    params: {bump: patch}
  - task: build and test
    file: ExpenseTracker/ci/build.yml
    params:
      file: build-output/expenseTracker-*.jar

- name: deploy
  plan:
  - get: ExpenseTracker
  - put: deployment
    params:
      path: ExpenseTracker-artifacts/expenseTracker-*.jar

